### page
GET http://localhost:8080/api/category/

### save category
POST http://localhost:8080/api/category/
content-type: application/json

{
  "name" : "Action",
  "description" : "Hola"
}


### page
GET http://localhost:8080/api/movie/

### save
POST http://localhost:8080/api/movie/
Content-Type: application/json

{
  "title": "aaaaaaaaa",
  "description": "",
  "category": {
    "id": 1
  }
}

